# yaml 配置
version: "3.7"
services:
  mysql8022:
    image: "mysql:8.0.22"
    ports:
      - "33061:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "blog"
      MYSQL_PASSWORD: "root"
    volumes:
      - ./init.sql:/data/application/init.sql
  redis:
    image: "redis"
    ports:
      - "26379:6379"
  blog:
    build: .
    command: sh -c "./wait-for.sh mysql8022:3306 redis:6379 -- ./blog ./conf/config.yaml"
    depends_on:
      - mysql8022
      - redis
    ports:
      - "8888:8081"